import type { Course } from "@/types";

export function getMockCourses(): Course[] {
  return [
    {
      _id: "mock-1",
      title: "Organizing Mega Crusades",
      description: "",
      slug: "organizing-mega-crusades",
      thumbnail: "/Images/course.png",
      instructor: "",
      category: "",
      price: 0,
      rating: 5,
      ratingCount: 0,
      level: "beginner",
      createdAt: "",
      updatedAt: "",
    },
    {
      _id: "mock-2",
      title: "Organizing Mega Crusades",
      description: "",
      slug: "organizing-mega-crusades-2",
      thumbnail: "/Images/course-1.png",
      instructor: "",
      category: "",
      price: 0,
      rating: 5,
      ratingCount: 0,
      level: "beginner",
      createdAt: "",
      updatedAt: "",
    },
    {
      _id: "mock-3",
      title: "Organizing Mega Crusades",
      description: "",
      slug: "organizing-mega-crusades-3",
      thumbnail: "/Images/course.png",
      instructor: "",
      category: "",
      price: 0,
      rating: 5,
      ratingCount: 0,
      level: "beginner",
      createdAt: "",
      updatedAt: "",
    },
    {
      _id: "mock-4",
      title: "Organizing Mega Crusades",
      description: "",
      slug: "organizing-mega-crusades-4",
      thumbnail: "/Images/course-1.png",
      instructor: "",
      category: "",
      price: 0,
      rating: 5,
      ratingCount: 0,
      level: "beginner",
      createdAt: "",
      updatedAt: "",
    },
  ];
}
